services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/app:/app/app    
      - ./db:/app/db     
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////app/db/library.db
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/src      # Hot-reload для React
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000  # Внутри Docker-сети
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:  # Том для БД (необязательно, но полезно для продакшена)