services:
  backend:
    build: ./server
    volumes:
      - ./server/app:/app/app    
      - ./db:/app/db     
    environment:
      - ENV=production
      - DATABASE_URL=sqlite:////app/db/library.db
    env_file:
      - ./server/.env
    networks:
      - app-network

  frontend:
    build: ./client
    environment:
      - VITE_API_URL=/api
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
