apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: epifanovv/devopslabs-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "sqlite:////app/db/library.db"
          envFrom:
            - secretRef:
                name: telegram-secret
          volumeMounts:
            - name: db-volume
              mountPath: /app/db
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "250m"
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: backend-pvc
