name: CD Pipeline

on:
  workflow_dispatch:  # Позволяет запустить вручную из GitHub интерфейса
  workflow_run:
    workflows: ["CI Pipeline"]  # Название твоего CI
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    environment: devopslabs

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devopslabs-frontend:latest ./client
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/devopslabs-frontend:latest

    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devopslabs-backend:latest ./server
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/devopslabs-backend:latest

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Set up KUBECONFIG
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/