name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client  # Ключевое исправление!

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Важно для получения истории коммитов

    - name: Verify lock file presence
      run: |
        ls -la
        if [ ! -f "package-lock.json" ]; then
          echo "##[error] package-lock.json not found in client directory!"
          exit 1
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: client/package-lock.json  # Явное указание пути

    - name: Install dependencies
      run: npm ci  # Требует наличия package-lock.json

    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm test -- --watchAll=false --ci
      env:
        CI: true

  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest -v tests/