name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client  # Все команды выполняются в папке client

    steps:
    - uses: actions/checkout@v4
    
    - name: Verify package-lock.json
      run: |
        pwd
        ls -la
        if [ ! -f "package-lock.json" ]; then
          echo "##[error] package-lock.json not found!"
          exit 1
        fi

    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json  # Явный путь к lock-файлу

    - name: Install dependencies
      run: npm ci  # Использует client/package-lock.json

    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm test -- --watchAll=false --ci
      env:
        CI: true

  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest -v tests/